spring:
  datasource:
    dynamic:
      primary: test1
      datasource:
        test1:
          url: jdbc:mysql://127.0.0.1/test1?characterEncoding=utf8&useSSL=true
          username: root
          password: root123
        test2:
          url: jdbc:mysql://127.0.0.1/test2?characterEncoding=utf8&useSSL=true
          username: root
          password: root123


